expname: biomolecule-app

defaults:
  - base_hydra_config
  - solver: poisson
  - _self_


# customization follows
gridstates:
  Nx_lvl: 128  # grid for level-set; not used in this example bc not free boundary
  Ny_lvl: 128  # grid for level-set; not used with level set is given functionally
  Nz_lvl: 128  # grid for level-set; not used with level set is given functionally
  Nx_eval: 256  # grid for evaluation/visualization/validation
  Ny_eval: 256  # grid for evaluation/visualization/validation
  Nz_eval: 256  # grid for evaluation/visualization/validation


model:
  model_type : "mlp"
  mlp:
    hidden_layers_m: 1
    hidden_dim_m: 3
    activation_m: "jnp.tanh"
    hidden_layers_p: 2
    hidden_dim_p: 10
    activation_p: "jnp.tanh"
  resnet:
    res_blocks_m : 3
    res_dim_m : 40
    activation_m : "nn.tanh"
    res_blocks_p : 3
    res_dim_p : 80
    activation_p : "nn.tanh"


solver:
  Nx_tr: 16  # grid for training
  Ny_tr: 16  # grid for training
  Nz_tr: 16  # grid for training
  num_epochs: 1000 # number of epochs to train
  print_rate: 10 # frequency of printing epochs and loss during training
  restart_from_checkpoint: false # whether to restart from an existing checkpoint
  restart_checkpoint_dir: /workspace/results/biomolecule-app/checkpoints
  algorithm: 0  # 0: regression normal derivatives, 1: neural network normal derivatives
  mgrad_over_pgrad_scalefactor: 1.0  # a scaling factor to amplify minus gradients
  switching_interval: 3  # domain switching interval
  version: 2  # 0: verbose/slow, 1: silent/fast, 2: refactored
  multi_gpu: False
  num_gpus_ddp: 1
  optim:
    optimizer_name: "custom" # options are "custom", "adam", "rmsprop"
    learning_rate: 1e-2
    sched:
      scheduler_name: "exponential" # options are "exponential", "polynomial"
      decay_rate: 0.96
  data_manager:
    refine: false
    refine_normals: false # if true will add extra points by moving grid points iteratively along minus normal of level-set function
    refine_lod: false # if true will add extra points by Octree using Kaolin

experiment:
  kirkwood:
    enable: false
    protein_name: case_0.pqr
    protein_path: inputs/kirkwood_test

  single_protein:
    enable: true
    protein_name: keytruda.pqr_ignore  # pdb:1ajj.pqr
    protein_path: inputs/pqr_input_mols
  
  multi_proteins:
    enable: False
    proteins_dir: inputs/pqr_input_mols
    num_gpus_batching: 3

  logging:
    checkpoint_interval: 500
    log_dir: ${hydra:runtime.output_dir}

