[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jax-dips"
version = "0.2.1"
authors = [
    { name = "Pouria Mistani", email = "p.a.mistani@gmail.com" },
    { name = "Samira Pakravan", email = "pakravans90@gmail.com" },
]
maintainers = [
    { name = "Pouria Mistani", email = "p.a.mistani@gmail.com" },
    { name = "Samira Pakravan", email = "pakravans90@gmail.com" },
]
description = "Differentiable 3D interfacial PDE solvers written in JAX using the Neural Bootstrapping Method."
requires-python = "~=3.8"
keywords = ["level-set", "PDE", "neural operators"]
license = { text = "LGPL-2.1-only" }
classifiers = [
    "Development Status :: 1 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Free Software Foundation",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Mathematics",
]

dynamic = ["dependencies", "readme"]

[project.urls]
"Homepage" = "https://github.com/JAX-DIPS/JAX-DIPS"
"Bug Tracker" = "https://github.com/JAX-DIPS/JAX-DIPS/issues"

[tool.setuptools.dynamic]
readme = { file = ["README.md"] }
dependencies = { file = ["requirements.txt"] }
