#!/usr/bin/env bash

IMAGE_NAME="jax_dip"
DOCKER_CMD="docker run \
    --network host \
    --gpus all \
    -p ${JUPYTER_PORT}:8888 \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v /etc/shadow:/etc/shadow:ro \
    -v $(pwd):/workspace \
    -e HOME=/workspace \
    -w /workspace"


usage() {
    echo "Please read README."
}


build() {
    set -x
    DOCKER_FILE="docker/Dockerfile"

    echo -e "Building ${DOCKER_FILE}..."
    docker build \
        -t ${IMAGE_NAME}:0.0.1 \
        -t ${IMAGE_NAME}:latest \
        -f ${DOCKER_FILE} .
}


dev() {
    local DEV_IMG=${IMAGE_NAME}
    PYTHONPATH='/workspace'

    while [[ $# -gt 0 ]]; do
        case $1 in
            -i|--image)
                DEV_IMG="$2"
                shift
                shift
                ;;
            *)
                echo "Unknown option $1"
                exit 1
                ;;
        esac
    done

    $DOCKER_CMD \
        --name jax_dip \
        -u $(id -u):$(id -u) \
        -e PYTHONPATH=$PYTHONPATH \
        -it --rm \
        ${DEV_IMG} \
        bash
}


case $1 in
    build)
        "$@"
        ;;
    dev)
        "$@"
        exit 0
        ;;
    *)
        usage
        ;;
esac
